### ISSUE TITLE
esmock 1.9.1 and eslint: Unable to resolve path to module 'esmock'

### ISSUE THREAD

**Issue by tripodsan** [iambumblehead/esmock#106]
With 1.9.1 I get:

```
> eslint .


/test/my.test.js
  17:20  error  Unable to resolve path to module 'esmock'  import/no-unresolved
```

the problem are the `exports` added in: https://github.com/iambumblehead/esmock/commit/96d2754ec0974a29d8323e3122515c4d0bbd77ea

also see:
https://nodejs.org/docs/latest-v16.x/api/packages.html#package-entry-points

when I add the 

```
  "main": "./src/esmockLoader.js",
```

again, it works.

**Comment by iambumblehead** [comment]
@tripodsan I apologize for breaking this. The PR you made has been published.

**Comment by aladdin-add** [comment]
it's just that plugin does not support `exports` yet. 

related: https://github.com/import-js/eslint-plugin-import/issues/2495

**Comment by tripodsan** [comment]
> it's just that plugin does not support `exports` yet.

yes, but also I'm not sure that the exports are correct this way:

```
  "exports": {
    "types": "./src/esmock.d.ts",
    "import": "./src/esmockLoader.js"
  },
```
@iambumblehead , what was the intention of those? if you look at the nodejs doc, all sub-package exports usually start with a `./`.
so, something like:

```
  "exports": {
    ".": "./src/esmockLoader.js"
    "./types": "./src/esmock.d.ts",
  },
```

would make more sense.

**Comment by aladdin-add** [comment]
I think it's working as expected, it's the same as:
```js
  "exports": {
    ".": {
       "import": "./src/esmockLoader.js",
       "types": "./src/esmock.d.ts"
     }
  },
```

**Comment by tripodsan** [comment]
ah right, those are [conditional exports](https://nodejs.org/docs/latest-v18.x/api/packages.html#conditional-exports)

**Comment by iambumblehead** [comment]
The pattern was changed in order to ensure support with newer versions of typescript. I accidentally removed too many fields and, to catch issues in the future, I'll try requesting reviews.

The export pattern is seen here https://nodejs.org/api/packages.html#approach-2-isolate-state and the pattern was recommended here https://github.com/iambumblehead/form-urlencoded/pull/45

The `exports['.']` and `exports['.'].import` patterns both seem like good suggestions. When there are "issues" with form-urlencoded, they are usually reported right away and no issues have been reported since https://github.com/iambumblehead/form-urlencoded/pull/45 was published

Anyway, I will need to study export patterns to learn more about them and to support them at esmock's resolver https://github.com/iambumblehead/resolvewithplus (for which the unit-tests were re-organized a day or two ago, in preparation for the unit-tests that would need to be added)

**Comment by iambumblehead** [comment]
would one of you review my PR here? https://github.com/iambumblehead/resolvewithplus/pull/24
