### ISSUE TITLE
Breakage in Node.js v20.6.0

### ISSUE THREAD

**Issue by mcollina** [iambumblehead/esmock#234]
The new loader API in v20.6.0 broke `esmock`

```

   FAIL  "should return un-mocked file"
    Cannot find package '[object Object]?esmk=1' imported from /Users/matteo/Repositories/esmock/src/esmock.js

    at nextResolveCall (file:///Users/matteo/Repositories/esmock/src/esmockLoader.js:71:7)
    at resolve (file:///Users/matteo/Repositories/esmock/src/esmockLoader.js:78:12)
```

I did try a quick replacement with the new `initialize`, but it looked a bit harder than expected.

cc @GeoffreyBooth for visibility.

**Comment by koshic** [comment]
issue comes from here:
<img width="744" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/5d2fe78d-6105-4a8e-99f3-859b998a3b67">

```shell
esmockModule -> moduleId, parent ../local/usesImportObjects.js file:///xxxxxx/esmock/tests/tests-node/esmock.node.global.test.js
esmockModule -> moduleFileURL {}
esmockModule -> moduleFileURL to string [object Object]
```

**Comment by koshic** [comment]
import.meta.resolve detection is incorrect, it assumes that import.meta.resolve is AsyncFunction:
<img width="532" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/fadbeacf-c7ce-4f44-9ab6-5142e496bb9c">

But, due to changes in 20.0.0
<img width="1053" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/beb374ac-2c8c-43ad-b9ff-7e24c103ad81">

And latest changes in 20.6.0
<img width="1037" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/ee6c6a15-e0c7-4763-ade0-18e2b4fea6bb">

import.meta.resolve is Function:
<img width="942" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/aa3d4644-6e93-4cfd-bf0c-6daa4b7a891e">

**Comment by koshic** [comment]
Another interesting point is https://github.com/nodejs/node/pull/49028

"Unflags import.meta.resolve making the second parentURL argument still gated behind the same --experimental-import-meta-resolve flag so that existing users would retain backwards compatibility, while the default behaviour becomes standards compliant."

So we have 2 different behaviors of import.meta.resolve depending on experimental flag.

I can successfully run a few tests with '--experimental-import-meta-resolve' and dirty patched resolve:
<img width="759" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/6cfbe38f-73ef-402e-b50f-0bf2fbbaa7bb">

But there is new error:
<img width="646" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/a888444e-d380-49b7-9c93-a3ee7cefd865">

**Comment by iambumblehead** [comment]
I do have time to investigate a solution today. Feel free to give any suggestions that should be considered.

**Comment by iambumblehead** [comment]
@koshic thanks for finding the cause and writing the nice summary. I understand.

**Comment by iambumblehead** [comment]
the native resolve function is broken in node 20.6
```javascript
const moduleId = '../local/usesNodeProcess.js'
const parent = 'file:///home/bumble/software/esmock/tests/tests-node/esmock.node.test.js'
console.log('resolved', import.meta.resolve(moduleId, parent)) // 'resolved {}'
```

**Comment by koshic** [comment]
```shell
mkdir -p xxx && touch xxx/1.mjs && touch xxx/2.mjs && \
echo 'import {resolve} from "path"; console.log(import.meta.resolve("./1.mjs", "file://" + resolve("./xxx/2.mjs")))' > 3.mjs && \
node --experimental-import-meta-resolve 3.mjs
```

works as expected in 20.5.0 & 20.6.0

**Comment by iambumblehead** [comment]
@koshic thanks eventually your solution will be used in this PR https://github.com/iambumblehead/esmock/pull/236

**Comment by iambumblehead** [comment]
The undefined `import` keyword issue breaks some tests using packages using `async await import`

**Comment by iambumblehead** [comment]
https://nodejs.org/api/esm.html#importmetaresolvespecifier

It seems `import.meta.resolve` will discontinue support for the 'parent' param, but indirectly continues support (for now) when the node process includes the flag `--experimental-import-meta-resolve`

Failing tests commented-out at the PR were caused by this recent change to import.meta.resolve. For example, [this test does not](https://github.com/iambumblehead/esmock/pull/236/files#diff-8babfcd7465bd2c8fbc30f2041e92631d44710de75059a550242cc6ba9e9d5d3R294) resolve the eslint module relative to parent.
```javascript
const fileURL = resolve.constructor.name === 'AsyncFunction'
    ? await resolve(id, parent) : resolve(id, parent)
// node v20.6, fileURL is incorrect, test fails
//  file:///home/bumble/software/esmock/node_modules/eslint/lib/api.js
// node v20.4, fileURL is correct, test passes
//  file:///home/bumble/software/esmock/tests/node_modules/eslint/lib/api.js
```

@koshic @mcollina what do you think? Maybe `import.meta.resolve` should be removed from esmock and the scripted [resolvewithplus](https://github.com/iambumblehead/resolvewithplus/tree/master/tests/tests-basic) used instead. Most users are using resolvewithplus already anyway, because `import.meta.resolve` has been undefined without the experimental flag.

**Comment by iambumblehead** [comment]
Another issue affecting node v20.6: https://github.com/iambumblehead/esmock/pull/237

The "load" hook is called with a nextLoad function that returns `{ source: null }` for CJS modules in node v20.6

looping in @tommy-mitchell

**Comment by iambumblehead** [comment]
https://nodejs.org/api/esm.html#loadurl-context-nextload

> The value of source can be omitted for type 'commonjs'. When a source is provided, all require calls from this module will be processed by the ESM loader with registered resolve and load hooks;  [...] This behavior for nullish source is temporary — in the future, nullish source will not be supported.

**Comment by iambumblehead** [comment]
Based on investigation, node v20.6 partially allows the loader to process cjs trees imported at [the global-CJS-imports test,][0] however, unknown factors cause the process to fail when certain cjs trees are imported multiple times.

The failing test uses a package called "meow". Possibly, the meow package could be opened and dependency trees imported there disabled and enabled to learn more information about the problem.


[0]: https://github.com/iambumblehead/esmock/blob/master/tests/tests-node/esmock.node.global.test.js#L67-L77

**Comment by iambumblehead** [comment]
I think the problem is meow has a circular dependency

**Comment by iambumblehead** [comment]
Some progress. There are no circular dependencies in meow.

esmock defined global values at require js sources, updating the source file to look like this,
```javascript
const { Date } = require('file:///import?esmk=4') // something like this...

// ...rest of the file
```

Newer versions of node have problems loading the path given to require. Error messages say the file is not found. Because 'file://import' is not a file, esmock was updated locally to use a known path instead, something like 'file:///home/bumble/esmock/esmockDummy.js?import?esmk=4' and this also caused the file not found error. An actual error,
```bash
✖ should optionally catch CJS circular imports (30.518101ms)
  Error: Cannot find module 'file:///home/bumble/software/esmock/src/esmockDummy.js?import?esmkTreeId=1&esmkModuleId=import&isfound=false&isesm=false&exportNames=console'
  Require stack:
  - /home/bumble/software/esmock/tests/node_modules/map-obj/index.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
      at require (node:internal/modules/esm/translators:177:30)
      at Object.<anonymous> (/home/bumble/software/esmock/tests/node_modules/map-obj/index.js:1:19)
      at loadCJSModule (node:internal/modules/esm/translators:207:3)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:233:7)
      at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
      at async file:///home/bumble/software/esmock/src/esmock.js:12:26
      at async TestContext.<anonymous> (file:///home/bumble/software/esmock/tests/tests-node/esmock.node.global.test.js:84:3)
      at async Test.run (node:internal/test_runner/test:582:9) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/home/bumble/software/esmock/tests/node_modules/map-obj/index.js' ]
  }
```

When a commonjs source like the one at the top of this comment is returned, the error occurs right away and the resolve hook is never called.

Replacing the require call with an object definition gets around the issue,
```javascript
const { Date } = global.mocks('file:///import?esmk=4')

// ...rest of the file
```

But there is yet another issue at the test using the meow package. This is the error
```bash
(node:157711) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
✖ should work when modules have CJS imports (354.79829ms)
  SyntaxError [Error]: /home/bumble/software/esmock/tests/node_modules/spdx-license-ids/index.json: Unexpected token 'i', "import {co"... is not valid JSON
      at parse (<anonymous>)
      at ModuleLoader.jsonStrategy (node:internal/modules/esm/translators:416:21)
      at callTranslator (node:internal/modules/esm/loader:265:14)
      at ModuleLoader.<anonymous> (node:internal/modules/esm/loader:269:24)
      at new ModuleJob (node:internal/modules/esm/module_job:65:26)
      at #createModuleJob (node:internal/modules/esm/loader:282:17)
      at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:240:34)
      at ModuleLoader.getModuleJobSync (node:internal/modules/esm/loader:226:17)
      at require (node:internal/modules/esm/translators:191:36)
      at Object.<anonymous> (/home/bumble/software/esmock/tests/node_modules/spdx-expression-parse/scan.js:4:11)
```

**Comment by iambumblehead** [comment]
Tests are passing at the branch that removes import.meta.resolve https://github.com/iambumblehead/esmock/pull/237 To get around error described in the last message, the load hook is scripted to only modify sources when the format is 'module' or 'commonjs'

If anyone would review that would be great.

One of the typescript tests is commented-out. Tests using the 'meow' package, including the commented-out typescript test, are big and not focused.  I believe the problem with the failing test exists in the test sources, but I've run out of energy for it and believe the current PR improves things and resolves issues at node v20.6.

If we revisit the typescript test, we might want to break it into smaller focused tests.

Please review @koshic @tommy-mitchell if you are available

**Comment by iambumblehead** [comment]
if import.meta.resolve is dropped, lets publish to new minor version 2.4.0

**Comment by koshic** [comment]
> Maybe `import.meta.resolve` should be removed from esmock

Agree - browser-like version of import.meta.resolve is useless for our purposes.

**Comment by iambumblehead** [comment]
esmock 2.4.0 is published

**Comment by iambumblehead** [comment]
The commented-out tests were affected by another issue: node's loader sometimes returns `{ source: undefined }` and other times returns `{ source: null }`

A solution for that issue is at the PR here https://github.com/iambumblehead/esmock/pull/238 and will likely be published soon.
